sudo: required
services:
  - docker

before_install:
  - docker build -t ahmedtaa/pg -f Dockerfile.dev .

script:
  - docker run ahmedtaa/pg npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "pg-docker"
  env: "PgDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-168742774878"
  bucket_path: "pg-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY